- name: Install repo
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo
  tags:
    - install

- name: Install Nginx
  package: name=nginx state=latest
  tags:
    - install

- name: Inatall config
  copy: src={{ item.src }} dest={{ item.dest }} mode=644
  with_items:
    - { src: nginx.conf, dest: /etc/nginx }
  tags:
    - config

- name: Remove default
  file: path=/etc/nginx/conf.d/default.conf state=absent
  tags:
    - config  

- name: Generate config
  template: src={{ item.src }} dest={{ item.dest }} mode=644
  with_items:
    - { src: service.http.conf.j2, dest: /etc/nginx/conf.d/service.http.conf }
  tags:
    - config

- name: Start Nginx
  systemd: name=nginx state=restarted daemon_reload=yes enabled=yes
  tags:
    - config
