- name: Push master specific k8s configs
  template: src={{ item.src }} dest={{ item.dest }}  mode=644
  with_items:
    - { src: etcd.conf.j2, dest: /etc/etcd/etcd.conf }
    - { src: apiserver.j2, dest: /etc/kubernetes/apiserver }
    - { src: scheduler.j2, dest: /etc/kubernetes/scheduler }    
    - { src: controller-manager.j2, dest: /etc/kubernetes/controller-manager }
    - { src: flannel-network.j2, dest: /etc/kubernetes/flannel-network }
    - { src: skydns-svc.yaml.j2, dest: /etc/kubernetes/skydns-svc.yaml }
  tags:
    - master_conf

- name: Push master service configs
  copy: src={{ item.src }} dest={{ item.dest }}  mode=644
  with_items:
    - { src: etcd.service, dest: /usr/lib/systemd/system/etcd.service }
    - { src: skydns-rc.yaml, dest: /etc/kubernetes/skydns-rc.yaml }
    - { src: dashboard-service.yaml, dest: /etc/kubernetes/dashboard-service.yaml }
    - { src: dashboard-controller.yaml, dest: /etc/kubernetes/dashboard-controller.yaml }
  tags:
    - master_conf

- name: Start etcd
  systemd: name=etcd enabled=yes state=restarted daemon_reload=yes
  when: "'master' in group_names"

- name: Configure cluster network
  shell: "{{ item }}"
  with_items:
    - etcdctl mkdir /kube-centos/network
    - etcdctl set /kube-centos/network/config < /etc/kubernetes/flannel-network
  ignore_errors: yes
  run_once: true
  tags:
    - flannel_conf

- name: Configure cluster DNS
  shell: "{{ item }}"
  with_items:
    - kubectl create -f /etc/kubernetes/skydns-rc.yaml
    - kubectl create -f /etc/kubernetes/skydns-svc.yaml
  ignore_errors: yes
  run_once: true
  tags:
    - dns

- name: Configure cluster Dashboard
  shell: "{{ item }}"
  with_items:
    - kubectl create -f /etc/kubernetes/dashboard-service.yaml
    - kubectl create -f /etc/kubernetes/dashboard-controller.yaml
  ignore_errors: yes
  run_once: true
  tags:
    - dashboard

- name: Enable and start services on master
  systemd: name={{ item }} enabled=yes state=restarted
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - flanneld
